from __future__ import annotations

from enum import StrEnum


class JobLifecycle(StrEnum):
    QUEUED = "QUEUED"
    ACTIVE = "ACTIVE"
    WAITING = "WAITING"
    PAUSED = "PAUSED"
    DRAINING = "DRAINING"
    SETTLED = "SETTLED"


class JobOutcome(StrEnum):
    SUCCESS = "SUCCESS"
    NOOP = "NOOP"
    EMPTY = "EMPTY"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class JobActivity(StrEnum):
    ANALYZING = "ANALYZING"
    DISCOVERING = "DISCOVERING"
    RESOLVING = "RESOLVING"
    TRANSFERRING = "TRANSFERRING"
    POSTPROCESSING = "POSTPROCESSING"
    VERIFYING = "VERIFYING"
    RECONCILING = "RECONCILING"


class WaitingReason(StrEnum):
    RETRY_BACKOFF = "RETRY_BACKOFF"
    RATE_LIMIT = "RATE_LIMIT"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    NETWORK_OFFLINE = "NETWORK_OFFLINE"
    LOW_DISK = "LOW_DISK"
    DESTINATION_UNAVAILABLE = "DESTINATION_UNAVAILABLE"
    DESTINATION_IDENTITY_UNCERTAIN = "DESTINATION_IDENTITY_UNCERTAIN"
    ENGINE_UNAVAILABLE = "ENGINE_UNAVAILABLE"
    SYSTEM_SLEEP = "SYSTEM_SLEEP"
    RESOURCE_LIMIT = "RESOURCE_LIMIT"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    DURABILITY_BLOCKED = "DURABILITY_BLOCKED"


class ControlIntent(StrEnum):
    NONE = "NONE"
    PAUSE_REQUESTED = "PAUSE_REQUESTED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"


class RunOutcome(StrEnum):
    SUCCESS = "SUCCESS"
    SUSPENDED = "SUSPENDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    CRASHED = "CRASHED"


class ItemLifecycle(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    WAITING = "WAITING"
    SETTLED = "SETTLED"


class ItemOutcome(StrEnum):
    SUCCESS = "SUCCESS"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ItemDisposition(StrEnum):
    SATISFIED = "SATISFIED"
    EXCLUDED = "EXCLUDED"
    UNSATISFIED = "UNSATISFIED"
    CANCELLED = "CANCELLED"


class ArtifactLifecycle(StrEnum):
    PLANNED = "PLANNED"
    MATERIALIZING = "MATERIALIZING"
    PRODUCED = "PRODUCED"
    VERIFIED = "VERIFIED"
    COMMITTED = "COMMITTED"
    FAILED = "FAILED"


class FileSystemState(StrEnum):
    UNKNOWN = "UNKNOWN"
    PRESENT = "PRESENT"
    MISSING = "MISSING"
    MODIFIED = "MODIFIED"
    CORRUPT = "CORRUPT"
    INACCESSIBLE = "INACCESSIBLE"


class DiscoveryCycleState(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    OPEN = "OPEN"
    SEALED = "SEALED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class DiscoveryCompleteness(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"


class InputKind(StrEnum):
    AUTO = "AUTO"
    URL = "URL"
    TAG = "TAG"
    USER = "USER"
    SEARCH = "SEARCH"


class JobKind(StrEnum):
    UNKNOWN = "UNKNOWN"
    DIRECT_FILE = "DIRECT_FILE"
    BOORU_GALLERY = "BOORU_GALLERY"
    WEB_GALLERY = "WEB_GALLERY"
    SINGLE_MEDIA = "SINGLE_MEDIA"
    COLLECTION_MEDIA = "COLLECTION_MEDIA"


class PathClaimState(StrEnum):
    CLAIMED = "CLAIMED"
    COMMITTED = "COMMITTED"
    RELEASED = "RELEASED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"


class FileCommitState(StrEnum):
    PREPARED = "PREPARED"
    COMMITTED = "COMMITTED"
    FAILED = "FAILED"
    UNCERTAIN = "UNCERTAIN"


class CommitOwnership(StrEnum):
    PRE_COMMIT = "PRE_COMMIT"
    COMMIT_OWNED = "COMMIT_OWNED"


class CleanupState(StrEnum):
    PENDING = "PENDING"
    RETRYING = "RETRYING"
    COMPLETED = "COMPLETED"
    ABANDONED_REVIEW_REQUIRED = "ABANDONED_REVIEW_REQUIRED"


class EnginePackEligibility(StrEnum):
    ACTIVE_ELIGIBLE = "ACTIVE_ELIGIBLE"
    FALLBACK_ELIGIBLE = "FALLBACK_ELIGIBLE"
    RETAIN_ONLY = "RETAIN_ONLY"
    REVOKED = "REVOKED"
    INCOMPATIBLE = "INCOMPATIBLE"
    CORRUPT = "CORRUPT"
